modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Razzokk/wireless-redstone/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/wirelessredstone"
logoFile = "assets/${mod_id}/icon.png"
authors = "${mod_author}"
description = '''${mod_description}'''
displayTest = "MATCH_VERSION"

[[dependencies]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
