# Increase memory available to gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=false
org.gradle.debug=false

# General
javaVersion=17

# Minecraft
mcVersion=1.20.4
mcVersionRange=[1.20.4,1.21)

# Mod properties
modId=wirelessredstone
modVersion=1.20.4-1.1.6
modName=WirelessRedstone
modDisplayName=Wireless Redstone
modGroup=rzk.wirelessredstone
modAuthor=Razzokk
modLicense=GPL-3.0
modDescription=A mod for Minecraft which adds Wireless Redstone mechanics

# Mappings
yarnMappings=1.20.4+build.3

# Fabric
loaderVersion=0.15.10
fabricApiVersion=0.97.0+1.20.4

# Forge
forgeVersion=49.1.0
forgeVersionRange=[49,)
loaderVersionRange=[49,)

# NeoForge
neoVersion=20.4.239
neoVersionRange=[20.4,)
neoLoaderVersionRange=[2,)

# Dependencies
# Optional
clothConfigVersion=13.0.121
modMenuVersion=9.0.0
# Runtime only
jeiVersion=17.3.0.49

# Repository
repoUrl=https://github.com/Razzokk/wireless-redstone

# Publishing
modrinthProjectId=2mBYHHZ5
curseForgeProjectId=409660
