modLoader = "javafml"
loaderVersion = "[32,)"
license="GNU GPL v3"

[[mods]]
modId = "wirelessredstone"
version = "${file.jarVersion}"
displayName = "Wireless Redstone"
logoFile = "wirelessredstone.png"
authors = "Razzokk"
description = '''Wireless Redstone brings wireless Redstone to your Minecraft World'''

[[dependencies.wirelessredstone]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wirelessredstone]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
