modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/Razzokk/Wireless-Redstone/issues"

[[mods]]
modId="wirelessredstone"
version="${file.jarVersion}"
displayName="Wireless Redstone" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/wireless-redstone-re"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#logoFile="wirelessredstone.png"
authors="Razzokk"
displayTest="MATCH_VERSION"
description='''A mod for Minecraft which adds Wireless Redstone mechanics'''

[[dependencies.wirelessredstone]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wirelessredstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
