import me.modmuss50.mpp.platforms.modrinth.ModrinthEnvironment
import mod.gradle.Mod
import net.minecraftforge.renamer.gradle.RenameJar
import org.gradle.jvm.tasks.Jar

// Reference: https://github.com/MinecraftForge/MDKExamples

plugins {
	id("loader")
	alias(libs.plugins.publish)
	alias(libs.plugins.forge.gradle)
	alias(libs.plugins.forge.renamer)
}

repositories {
	minecraft.mavenizer(this)
	maven(fg.forgeMaven)
	maven(fg.minecraftLibsMaven)
}

dependencies {
	implementation(minecraft.dependency(libs.forge.get().toString()))
	annotationProcessor(variantOf(libs.mixin) { classifier("processor") })
	api(renamer.dependency(libs.clothconfig.forge.get().toString()))
}

minecraft {
	mappings(libs.parchment.get().name, "${libs.versions.parchment.get()}-${libs.versions.minecraft.get()}")

	val common = project(":common")
	accessTransformer = common.files("src/main/resources/META-INF/accesstransformer.cfg")

	runs {
		configureEach {
			systemProperty("eventbus.api.strictRuntimeChecks", "true")
			systemProperty("mixin.env.remapRefMap", "true")
			systemProperty("mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg")
			systemProperty("forge.logging.markers", "REGISTRIES")
			systemProperty("forge.logging.console.level", "debug")
			jvmArgs("-Dmixin.debug.verbose=true", "-Dmixin.debug.export=true")
		}

		create("client") {
			workingDir = file("run/client")
			args("--username", "dev")
		}

		create("server") {
			workingDir = file("run/server")
			args("--nogui")
		}
	}
}

// Only for Minecraft 1.21.11 or lower
renamer {
	enableMixinRefmaps {
		config("${Mod.ID}.forge.mixins.json")
	}

	// Creates a task named 'renameJar'
	classes(tasks.named<Jar>("jar")) {
		// Need to use the generated mappings, which includes things generated by the annotation processor
		mappings(renamer.mixin.generatedMappings)
		// Just use the final output jar, no need for a separate renamed jar
		archiveClassifier = ""
	}

	// Needs to be after the call of `minecraft.dependency`, also stated by error message
	mappings(minecraft.dependency.toSrg)
}

// Mixin configuration (requires plugin: id("org.spongepowered.mixin") version "0.7.+")
// Does not work because not compatible with newer gradle versions
// Workaround: reference main.refmap.json in the mixin file

//mixin {
//	add(sourceSets.main.get(), "$modId.refmap.json")
//	config("$modId.mixins.json")
//
//	if (project.hasProperty("debug")) {
//		val debug = this.debug as DynamicProperties
//		debug.setProperty("verbose", true)
//		debug.setProperty("export", true)
//		setDebug(debug)
//	}
//}

publishMods {
	val changelogProvider = rootProject.extra["changelogProvider"] as Provider<*>
	val minecraftVersion = libs.versions.minecraft.get()

	// Need to use the renameJar jar output
	file.set(tasks.named<RenameJar>("renameJar").get().output)
	modLoaders.add("forge")
	changelog = changelogProvider.get() as String
	displayName = "[Forge $minecraftVersion] ${Mod.VERSION} ${Mod.NAME}"
	version = "${Mod.VERSION}+$minecraftVersion-forge"
	type = STABLE

	curseforge {
		projectId = Mod.CURSEFORGE_PROJECT_ID
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		minecraftVersions.add(minecraftVersion)

		javaVersions.add(JavaVersion.toVersion(Mod.JAVA))

		client = true
		server = true

		optional("cloth-config")
	}

	modrinth {
		projectId = Mod.MODRINTH_PROJECT_ID
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		minecraftVersions.add(minecraftVersion)

		environment.set(ModrinthEnvironment.CLIENT_AND_SERVER)

		optional("cloth-config")
	}
}
