name: Build and Publish
on: push

env:
  JAVA_VERSION: 17
  MC_VERSION: 1.20.1
  MOD_LOADER: Fabric
  MOD_NAME: wirelessredstone
  MOD_VERSION: 1.20.1-1.0.0
  CURSEFORGE_ID: 409660
  MODRINTH_ID: 2mBYHHZ5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup jdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Generate changes file
        run: awk '/^##\s\[.*\]/ {p = ($2 == "[Unreleased]")}; p' CHANGELOG.md > CHANGES.md

      - name: get info
        run: |
          echo "JAR_NAME=$(ls build/libs/*)" >> $GITHUB_ENV
          echo $(ls)
          echo $(CHANGELOG.md)
          echo $(CHANGES.md)
          echo $(GITHUB_REF)


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: false
    steps:
      - name: Publish to CurseForge & Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ env.MOD_NAME }}
          version: ${{ env.MOD_VERSION }}
          changelog-file: CHANGES.md

          java: ${{ env.JAVA_VERSION }}
