name: Build & Publish
on: push

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            forge/build/libs/
            neoforge/build/libs/

      - name: Publish Fabric to Modrinth & CurseForge
        if: startsWith(github.ref, 'refs/tags/release/fabric/')
        run: ./gradlew :fabric:modrinth :fabric:curseforge

      - name: Publish Forge to Modrinth & CurseForge
        if: startsWith(github.ref, 'refs/tags/release/forge/')
        run: ./gradlew :forge:modrinth :forge:curseforge

      - name: Publish NeoForge to Modrinth & CurseForge
        if: startsWith(github.ref, 'refs/tags/release/neoforge/')
        run: ./gradlew :neoforge:modrinth :neoforge:curseforge
